# Generated by Django 6.0.4 on 2026-05-12 01:49

from django.db import migrations

def populate_status(apps, schemaeditor): # This function will be run when we apply this migration. It populates the Status table with some initial data.
    entries = { # This is a dictionary of status entries we want to add to the database. The key is the name of the status, and the value is its description.
        "published": "A post available for all to view", # Note: "published" is misspelled as "publised" in the original code. You may want to correct this.
        "draft": "A post only visible to the aurthor", #  Note: "author" is misspelled as "aurthor" in the original code. You may want to correct this.
        "archived": "An older post visible only to the logged user" # Note: "logged in user" is misspelled as "logged user" in the original code. You may want to correct this.
    }
    Status = apps.get_model('posts', 'Status') # Get the Status model from the "posts" app
    for key, value in entries.items(): # Loop through each entry in the dictionary
        status_obj = Status(name=key, description=value) # Create a new Status object with the name and description from the dictionary
        status_obj.save() # Save the new Status object to the database
        
class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status'),
    ]

    operations = [
        migrations.RunPython(populate_status) # This tells Django to run the populate_status function when this migration is applied. It will add the initial status entries to the database.
    ]

    
